x-common-volumes: &common-volumes
  - ./:/MoneyPrinterTurbo
  - ./tts:/root/.local/share/tts

services:
  webui:
    build:
      context: .
      dockerfile: Dockerfile
    image: "video-generator-webui"
    ports:
      - "8501:8501"
    command:
      [
        "streamlit",
        "run",
        "./webui/Main.py",
        "--browser.serverAddress=127.0.0.1",
        "--server.enableCORS=True",
        "--browser.gatherUsageStats=False",
      ]
    volumes: *common-volumes
    restart: always
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: "video-generator-api"
    ports:
      - "8080:8080"
    command: ["python3", "main.py"]
    volumes: *common-volumes
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  ollama:
    image: ollama/ollama:latest
    container_name: "ollama"
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    environment:
      - OLLAMA_KEEP_ALIVE=60
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  ollama: {}
