x-common-volumes: &common-volumes
  - ./:/MoneyPrinterTurbo

services:
  webui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "webui"
    ports:
      - "8501:8501"
    command:
      [
        "streamlit",
        "run",
        "./webui/Main.py",
        "--browser.serverAddress=127.0.0.1",
        "--server.enableCORS=True",
        "--browser.gatherUsageStats=False",
      ]
    volumes: *common-volumes
    restart: always
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "api"
    ports:
      - "8080:8080"
    command: ["python3", "main.py"]
    volumes: *common-volumes
    restart: always
  ollama:
    build:
      context: .
      dockerfile: ./Dockerfile.ollama
    image: ollama
    container_name: ollama
    entrypoint: /tmp/run_ollama.sh
    ports:
      - 11434:11434
    volumes:
      - ollama:/root/.ollama
    pull_policy: always
    tty: true
    restart: always

volumes:
  ollama: {}
