x-common-volumes: &common-volumes
  - ./:/MoneyPrinterTurbo

services:
  webui:
    build:
      context: .
      dockerfile: Dockerfile
    image: "video-generator-webui"
    ports:
      - "8501:8501"
    command:
      [
        "streamlit",
        "run",
        "./webui/Main.py",
        "--browser.serverAddress=127.0.0.1",
        "--server.enableCORS=True",
        "--browser.gatherUsageStats=False",
      ]
    volumes: *common-volumes
    restart: always
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: "video-generator-api"
    ports:
      - "8080:8080"
    command: ["python3", "main.py"]
    volumes: *common-volumes
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      replicas: 4
      update_config:
        parallelism: 1
        order: start-first

  # ollama:
  #   image: ollama/ollama:rocm
  #   container_name: "ollama"
  #   ports:
  #     - "11434:11434"
  #   volumes:
  #     - ollama:/root/.ollama
  #   restart: always
  #   environment:
  #     - "HSA_OVERRIDE_GFX_VERSION=9.0.6"

volumes:
  ollama: {}
